### ISSUE TITLE
Login failure on Win10

### ISSUE THREAD

**Issue by Zerefdev** [hackjutsu/Lepton#234] opened 2017-10-22 16:46 UTC
The more we know about your system and use case, the more easily and likely we can help.

#### Environment info
* OS: **Win 10 Pro**
* App Version (`Command/Ctrl + ,`): **1.5.0**

#### Description of the problem / feature request / question:
**After installing the app, I logged in and made some snippets, later I reloaded and the login page has been shown, I put my login info, it loads but it puts me again to log in page...**

#### If possible, provide a sample gist or screenshot:
![1](https://user-images.githubusercontent.com/25670700/31864172-4a0a73ca-b759-11e7-97ab-1e47e2d41426.PNG)

![2](https://user-images.githubusercontent.com/25670700/31864173-4a37a9e4-b759-11e7-9fed-a3bbaf5dfc12.PNG)

![3](https://user-images.githubusercontent.com/25670700/31864174-4a6e1268-b759-11e7-87eb-daab6b29b0f9.PNG)

#### If possible, provide the log files
**No log file has been generated!**
- Mac: `~/Library/Application Support/Lepton/logs`
- Windows: `C:\Users\<username>\AppData\Roaming\Lepton\logs`
- Linux: `~/.cached/Lepton/logs`
>The [debug mode](https://github.com/hackjutsu/Lepton/wiki) is recommended when producing the logs. 
>You can send your log file to cosmo.lepton@gmail.com if don't want to post it here.

**Comment by hackjutsu** [comment] 2017-10-23 03:53
Thanks for reporting. I might not be able to look into the issue without a log file. Let's keep this  open and see whether someone else encounters the same issue and happens to have a log file.

**Comment by Zerefdev** [comment] 2017-10-24 17:12
Oups! I was looking for log file in the wrong directory Local/Lepton instead of Roaming..

**Before enabling debug mode**
[2017-10-24T16.57.02.814Z.log](https://github.com/hackjutsu/Lepton/files/1411757/2017-10-24T16.57.02.814Z.log)

**After enabling it** (_and see the screenshot below_)
Stuck there more than 5 min
[2017-10-24T17.05.11.484Z.log](https://github.com/hackjutsu/Lepton/files/1411758/2017-10-24T17.05.11.484Z.log)

![lepton](https://user-images.githubusercontent.com/25670700/31957394-eebabe16-b8ee-11e7-8e20-99b90e96f995.PNG)

**Comment by hackjutsu** [comment] 2017-10-26 21:20
@Zerefdev 

The debug mode doesn't seem to be enabled since only 'info' level is shown. But according to the logs available, some of the network request is rejected for unknown reason and Lepton is reset to original login state (this is by design). 

Maybe I can release an alpha version with debug enabled by default.

**Comment by Zerefdev** [comment] 2017-10-27 13:45
@hackjutsu

Yes, please.

**Comment by hackjutsu** [comment] 2017-10-31 06:44
@Zerefdev Please try to reproduce the issue on [v1.5.1-alpha](https://github.com/hackjutsu/Lepton/releases/tag/v1.5.1-alpha). It should have the debug turned on by default.

**Comment by hackjutsu** [comment] 2017-11-08 03:39
This might be fixed by deleting `C:\Users\<username>\AppData\Roaming\Lepton\`.

**Comment by Zerefdev** [comment] 2017-11-12 22:57
It works fine now.
Thanks

**Closed** 2017-11-13 04:13 UTC
Labels: bug, more information needed

**Comment by azhe403** [comment] 2021-07-29 12:25
Just reopen Lepton, no stuck anymore
